#In the PASSWORD section you have to write the password in base64 strings.
#echo -n 'PASSWORD' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: PASSWORD

